// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务状态枚举
type TaskStatus int32

const (
	TaskStatus_TASK_PENDING   TaskStatus = 0
	TaskStatus_TASK_RUNNING   TaskStatus = 1
	TaskStatus_TASK_COMPLETED TaskStatus = 2
	TaskStatus_TASK_FAILED    TaskStatus = 3
	TaskStatus_TASK_TIMEOUT   TaskStatus = 4
	TaskStatus_TASK_CANCELLED TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_PENDING",
		1: "TASK_RUNNING",
		2: "TASK_COMPLETED",
		3: "TASK_FAILED",
		4: "TASK_TIMEOUT",
		5: "TASK_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_PENDING":   0,
		"TASK_RUNNING":   1,
		"TASK_COMPLETED": 2,
		"TASK_FAILED":    3,
		"TASK_TIMEOUT":   4,
		"TASK_CANCELLED": 5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// 任务类型枚举
type TaskType int32

const (
	TaskType_TUNNEL_CREATE    TaskType = 0 // 创建隧道
	TaskType_TUNNEL_CLOSE     TaskType = 1 // 关闭隧道
	TaskType_COMMAND_EXECUTE  TaskType = 2 // 执行命令
	TaskType_HARDWARE_CONTROL TaskType = 3 // 硬件控制
	TaskType_NETWORK_PROBE    TaskType = 4 // 网络探测
	TaskType_FILE_TRANSFER    TaskType = 5 // 文件传输
	TaskType_SCRIPT_EXECUTE   TaskType = 6 // 脚本执行
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TUNNEL_CREATE",
		1: "TUNNEL_CLOSE",
		2: "COMMAND_EXECUTE",
		3: "HARDWARE_CONTROL",
		4: "NETWORK_PROBE",
		5: "FILE_TRANSFER",
		6: "SCRIPT_EXECUTE",
	}
	TaskType_value = map[string]int32{
		"TUNNEL_CREATE":    0,
		"TUNNEL_CLOSE":     1,
		"COMMAND_EXECUTE":  2,
		"HARDWARE_CONTROL": 3,
		"NETWORK_PROBE":    4,
		"FILE_TRANSFER":    5,
		"SCRIPT_EXECUTE":   6,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

// Agent注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                              // Agent唯一ID
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                                                                             // Agent版本
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`                                                                               // 所在区域
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                                                                   // 支持的协议能力 ["ssh", "telnet", "rdp", "ipmi", "snmp"]
	Resources     *ResourceLimits        `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`                                                                         // 资源限制
	NetworkInfo   *NetworkInfo           `protobuf:"bytes,6,opt,name=network_info,json=networkInfo,proto3" json:"network_info,omitempty"`                                                  // 网络信息
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	AuthToken     string                 `protobuf:"bytes,8,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`                                                        // 认证令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetResources() *ResourceLimits {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *RegisterRequest) GetNetworkInfo() *NetworkInfo {
	if x != nil {
		return x.NetworkInfo
	}
	return nil
}

func (x *RegisterRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// Agent注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AgentToken    string                 `protobuf:"bytes,3,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"` // OPS分配的令牌
	Config        *AgentConfig           `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`                           // 下发的配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *RegisterResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// 资源限制
type ResourceLimits struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaxConcurrentSessions int32                  `protobuf:"varint,1,opt,name=max_concurrent_sessions,json=maxConcurrentSessions,proto3" json:"max_concurrent_sessions,omitempty"` // 最大并发会话数
	MaxMemoryMb           int32                  `protobuf:"varint,2,opt,name=max_memory_mb,json=maxMemoryMb,proto3" json:"max_memory_mb,omitempty"`                               // 最大内存使用(MB)
	MaxCpuPercent         int32                  `protobuf:"varint,3,opt,name=max_cpu_percent,json=maxCpuPercent,proto3" json:"max_cpu_percent,omitempty"`                         // 最大CPU使用率
	SessionTimeoutSeconds int32                  `protobuf:"varint,4,opt,name=session_timeout_seconds,json=sessionTimeoutSeconds,proto3" json:"session_timeout_seconds,omitempty"` // 会话超时时间
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceLimits) GetMaxConcurrentSessions() int32 {
	if x != nil {
		return x.MaxConcurrentSessions
	}
	return 0
}

func (x *ResourceLimits) GetMaxMemoryMb() int32 {
	if x != nil {
		return x.MaxMemoryMb
	}
	return 0
}

func (x *ResourceLimits) GetMaxCpuPercent() int32 {
	if x != nil {
		return x.MaxCpuPercent
	}
	return 0
}

func (x *ResourceLimits) GetSessionTimeoutSeconds() int32 {
	if x != nil {
		return x.SessionTimeoutSeconds
	}
	return 0
}

// 网络信息
type NetworkInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LocalIp         string                 `protobuf:"bytes,1,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`                                                                                                 // 本地IP
	PublicIp        string                 `protobuf:"bytes,2,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`                                                                                              // 公网IP
	NetworkSegments []string               `protobuf:"bytes,3,rep,name=network_segments,json=networkSegments,proto3" json:"network_segments,omitempty"`                                                                         // 管理的网段
	NetworkLatency  map[string]int32       `protobuf:"bytes,4,rep,name=network_latency,json=networkLatency,proto3" json:"network_latency,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 到各区域的延迟
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkInfo) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *NetworkInfo) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *NetworkInfo) GetNetworkSegments() []string {
	if x != nil {
		return x.NetworkSegments
	}
	return nil
}

func (x *NetworkInfo) GetNetworkLatency() map[string]int32 {
	if x != nil {
		return x.NetworkLatency
	}
	return nil
}

// Agent配置
type AgentConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,1,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`                                       // 心跳间隔
	PluginConfigs            map[string]string      `protobuf:"bytes,2,rep,name=plugin_configs,json=pluginConfigs,proto3" json:"plugin_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 插件配置
	AllowedTargets           []string               `protobuf:"bytes,3,rep,name=allowed_targets,json=allowedTargets,proto3" json:"allowed_targets,omitempty"`                                                                        // 允许访问的目标
	DebugMode                bool                   `protobuf:"varint,4,opt,name=debug_mode,json=debugMode,proto3" json:"debug_mode,omitempty"`                                                                                      // 调试模式
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentConfig) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetPluginConfigs() map[string]string {
	if x != nil {
		return x.PluginConfigs
	}
	return nil
}

func (x *AgentConfig) GetAllowedTargets() []string {
	if x != nil {
		return x.AllowedTargets
	}
	return nil
}

func (x *AgentConfig) GetDebugMode() bool {
	if x != nil {
		return x.DebugMode
	}
	return false
}

// Agent -> OPS 消息
type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MessageId string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_TaskResult
	//	*AgentMessage_ErrorReport
	//	*AgentMessage_Metrics
	//	*AgentMessage_PluginStatus
	//	*AgentMessage_ConnectionReport
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentMessage) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *HeartbeatData {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *AgentMessage) GetErrorReport() *ErrorReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ErrorReport); ok {
			return x.ErrorReport
		}
	}
	return nil
}

func (x *AgentMessage) GetMetrics() *MetricsData {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentMessage) GetPluginStatus() *PluginStatus {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_PluginStatus); ok {
			return x.PluginStatus
		}
	}
	return nil
}

func (x *AgentMessage) GetConnectionReport() *ConnectionReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ConnectionReport); ok {
			return x.ConnectionReport
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *HeartbeatData `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,5,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type AgentMessage_ErrorReport struct {
	ErrorReport *ErrorReport `protobuf:"bytes,6,opt,name=error_report,json=errorReport,proto3,oneof"`
}

type AgentMessage_Metrics struct {
	Metrics *MetricsData `protobuf:"bytes,7,opt,name=metrics,proto3,oneof"`
}

type AgentMessage_PluginStatus struct {
	PluginStatus *PluginStatus `protobuf:"bytes,8,opt,name=plugin_status,json=pluginStatus,proto3,oneof"`
}

type AgentMessage_ConnectionReport struct {
	ConnectionReport *ConnectionReport `protobuf:"bytes,9,opt,name=connection_report,json=connectionReport,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_TaskResult) isAgentMessage_Payload() {}

func (*AgentMessage_ErrorReport) isAgentMessage_Payload() {}

func (*AgentMessage_Metrics) isAgentMessage_Payload() {}

func (*AgentMessage_PluginStatus) isAgentMessage_Payload() {}

func (*AgentMessage_ConnectionReport) isAgentMessage_Payload() {}

// OPS -> Agent 消息
type OpsMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Priority  int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"` // 消息优先级 1=低 5=高
	// Types that are valid to be assigned to Payload:
	//
	//	*OpsMessage_Task
	//	*OpsMessage_Config
	//	*OpsMessage_HealthCheck
	//	*OpsMessage_PluginCmd
	//	*OpsMessage_Shutdown
	//	*OpsMessage_TunnelRequest
	Payload       isOpsMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpsMessage) Reset() {
	*x = OpsMessage{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpsMessage) ProtoMessage() {}

func (x *OpsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpsMessage.ProtoReflect.Descriptor instead.
func (*OpsMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *OpsMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *OpsMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OpsMessage) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *OpsMessage) GetPayload() isOpsMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OpsMessage) GetTask() *TaskAssignment {
	if x != nil {
		if x, ok := x.Payload.(*OpsMessage_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *OpsMessage) GetConfig() *ConfigUpdate {
	if x != nil {
		if x, ok := x.Payload.(*OpsMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *OpsMessage) GetHealthCheck() *HealthCheck {
	if x != nil {
		if x, ok := x.Payload.(*OpsMessage_HealthCheck); ok {
			return x.HealthCheck
		}
	}
	return nil
}

func (x *OpsMessage) GetPluginCmd() *PluginCommand {
	if x != nil {
		if x, ok := x.Payload.(*OpsMessage_PluginCmd); ok {
			return x.PluginCmd
		}
	}
	return nil
}

func (x *OpsMessage) GetShutdown() *ShutdownCommand {
	if x != nil {
		if x, ok := x.Payload.(*OpsMessage_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *OpsMessage) GetTunnelRequest() *TunnelRequest {
	if x != nil {
		if x, ok := x.Payload.(*OpsMessage_TunnelRequest); ok {
			return x.TunnelRequest
		}
	}
	return nil
}

type isOpsMessage_Payload interface {
	isOpsMessage_Payload()
}

type OpsMessage_Task struct {
	Task *TaskAssignment `protobuf:"bytes,4,opt,name=task,proto3,oneof"`
}

type OpsMessage_Config struct {
	Config *ConfigUpdate `protobuf:"bytes,5,opt,name=config,proto3,oneof"`
}

type OpsMessage_HealthCheck struct {
	HealthCheck *HealthCheck `protobuf:"bytes,6,opt,name=health_check,json=healthCheck,proto3,oneof"`
}

type OpsMessage_PluginCmd struct {
	PluginCmd *PluginCommand `protobuf:"bytes,7,opt,name=plugin_cmd,json=pluginCmd,proto3,oneof"`
}

type OpsMessage_Shutdown struct {
	Shutdown *ShutdownCommand `protobuf:"bytes,8,opt,name=shutdown,proto3,oneof"`
}

type OpsMessage_TunnelRequest struct {
	TunnelRequest *TunnelRequest `protobuf:"bytes,9,opt,name=tunnel_request,json=tunnelRequest,proto3,oneof"`
}

func (*OpsMessage_Task) isOpsMessage_Payload() {}

func (*OpsMessage_Config) isOpsMessage_Payload() {}

func (*OpsMessage_HealthCheck) isOpsMessage_Payload() {}

func (*OpsMessage_PluginCmd) isOpsMessage_Payload() {}

func (*OpsMessage_Shutdown) isOpsMessage_Payload() {}

func (*OpsMessage_TunnelRequest) isOpsMessage_Payload() {}

// 心跳数据
type HeartbeatData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                                                           // online/offline/busy
	ActiveSessions  int32                  `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`                                                                    // 活跃会话数
	CpuUsagePercent float32                `protobuf:"fixed32,3,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`                                                              // CPU使用率
	MemoryUsageMb   float32                `protobuf:"fixed32,4,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`                                                                    // 内存使用量
	UptimeSeconds   int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`                                                                       // 运行时间
	PluginStatus    map[string]string      `protobuf:"bytes,6,rep,name=plugin_status,json=pluginStatus,proto3" json:"plugin_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 插件状态
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatData) Reset() {
	*x = HeartbeatData{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatData) ProtoMessage() {}

func (x *HeartbeatData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatData.ProtoReflect.Descriptor instead.
func (*HeartbeatData) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatData) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *HeartbeatData) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *HeartbeatData) GetMemoryUsageMb() float32 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

func (x *HeartbeatData) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HeartbeatData) GetPluginStatus() map[string]string {
	if x != nil {
		return x.PluginStatus
	}
	return nil
}

// 任务结果
type TaskResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CommandId       string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status          TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=agent.TaskStatus" json:"status,omitempty"`
	ResultData      string                 `protobuf:"bytes,4,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"` // JSON格式的结果数据
	ErrorMessage    string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,6,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_PENDING
}

func (x *TaskResult) GetResultData() string {
	if x != nil {
		return x.ResultData
	}
	return ""
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *TaskResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 错误报告
type ErrorReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Component     string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"` // 出错的组件
	StackTrace    string                 `protobuf:"bytes,4,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorReport) Reset() {
	*x = ErrorReport{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReport) ProtoMessage() {}

func (x *ErrorReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReport.ProtoReflect.Descriptor instead.
func (*ErrorReport) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorReport) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ErrorReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ErrorReport) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ErrorReport) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *ErrorReport) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// 监控指标数据
type MetricsData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests         int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	SuccessfulRequests    int64                  `protobuf:"varint,2,opt,name=successful_requests,json=successfulRequests,proto3" json:"successful_requests,omitempty"`
	FailedRequests        int64                  `protobuf:"varint,3,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	AverageResponseTimeMs float32                `protobuf:"fixed32,4,opt,name=average_response_time_ms,json=averageResponseTimeMs,proto3" json:"average_response_time_ms,omitempty"`
	ConcurrentSessions    int32                  `protobuf:"varint,5,opt,name=concurrent_sessions,json=concurrentSessions,proto3" json:"concurrent_sessions,omitempty"`
	ThroughputMbps        float32                `protobuf:"fixed32,6,opt,name=throughput_mbps,json=throughputMbps,proto3" json:"throughput_mbps,omitempty"`
	ProtocolMetrics       map[string]float32     `protobuf:"bytes,7,rep,name=protocol_metrics,json=protocolMetrics,proto3" json:"protocol_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // 各协议的指标
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MetricsData) Reset() {
	*x = MetricsData{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsData) ProtoMessage() {}

func (x *MetricsData) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsData.ProtoReflect.Descriptor instead.
func (*MetricsData) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *MetricsData) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *MetricsData) GetSuccessfulRequests() int64 {
	if x != nil {
		return x.SuccessfulRequests
	}
	return 0
}

func (x *MetricsData) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *MetricsData) GetAverageResponseTimeMs() float32 {
	if x != nil {
		return x.AverageResponseTimeMs
	}
	return 0
}

func (x *MetricsData) GetConcurrentSessions() int32 {
	if x != nil {
		return x.ConcurrentSessions
	}
	return 0
}

func (x *MetricsData) GetThroughputMbps() float32 {
	if x != nil {
		return x.ThroughputMbps
	}
	return 0
}

func (x *MetricsData) GetProtocolMetrics() map[string]float32 {
	if x != nil {
		return x.ProtocolMetrics
	}
	return nil
}

// 插件状态
type PluginStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // loaded/unloaded/error
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Config        map[string]string      `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStatus) Reset() {
	*x = PluginStatus{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatus) ProtoMessage() {}

func (x *PluginStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatus.ProtoReflect.Descriptor instead.
func (*PluginStatus) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *PluginStatus) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *PluginStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PluginStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PluginStatus) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// 连接报告
type ConnectionReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Target           string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Protocol         string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // ssh/telnet/rdp/ipmi/snmp
	Connected        bool                   `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	ConnectionTimeMs int64                  `protobuf:"varint,4,opt,name=connection_time_ms,json=connectionTimeMs,proto3" json:"connection_time_ms,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectionReport) Reset() {
	*x = ConnectionReport{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionReport) ProtoMessage() {}

func (x *ConnectionReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionReport.ProtoReflect.Descriptor instead.
func (*ConnectionReport) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ConnectionReport) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ConnectionReport) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ConnectionReport) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ConnectionReport) GetConnectionTimeMs() int64 {
	if x != nil {
		return x.ConnectionTimeMs
	}
	return 0
}

func (x *ConnectionReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 任务分配
type TaskAssignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CommandId      string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	TaskType       TaskType               `protobuf:"varint,3,opt,name=task_type,json=taskType,proto3,enum=agent.TaskType" json:"task_type,omitempty"`
	Target         string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`                            // 目标主机地址
	TargetPort     int32                  `protobuf:"varint,5,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"` // 目标端口
	Credentials    *Credentials           `protobuf:"bytes,6,opt,name=credentials,proto3" json:"credentials,omitempty"`                  // 认证信息
	Payload        string                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`                          // 任务载荷(JSON)
	TimeoutSeconds int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Priority       int32                  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	Options        map[string]string      `protobuf:"bytes,10,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *TaskAssignment) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TUNNEL_CREATE
}

func (x *TaskAssignment) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TaskAssignment) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *TaskAssignment) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *TaskAssignment) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *TaskAssignment) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *TaskAssignment) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskAssignment) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// 认证信息
type Credentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AuthMethod    string                 `protobuf:"bytes,5,opt,name=auth_method,json=authMethod,proto3" json:"auth_method,omitempty"` // password/publickey/none
	Extra         map[string]string      `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *Credentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Credentials) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *Credentials) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Credentials) GetAuthMethod() string {
	if x != nil {
		return x.AuthMethod
	}
	return ""
}

func (x *Credentials) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// 配置更新
type ConfigUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion   string                 `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Configs         map[string]string      `protobuf:"bytes,2,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RestartRequired bool                   `protobuf:"varint,3,opt,name=restart_required,json=restartRequired,proto3" json:"restart_required,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigUpdate) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *ConfigUpdate) GetConfigs() map[string]string {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ConfigUpdate) GetRestartRequired() bool {
	if x != nil {
		return x.RestartRequired
	}
	return false
}

// 健康检查
type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckId       string                 `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	Components    []string               `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"` // 要检查的组件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *HealthCheck) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *HealthCheck) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

// 插件命令
type PluginCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"` // load/unload/reload/configure
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginCommand) Reset() {
	*x = PluginCommand{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCommand) ProtoMessage() {}

func (x *PluginCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCommand.ProtoReflect.Descriptor instead.
func (*PluginCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *PluginCommand) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *PluginCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *PluginCommand) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// 关闭命令
type ShutdownCommand struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Reason             string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	GracePeriodSeconds int32                  `protobuf:"varint,2,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"`
	ForceShutdown      bool                   `protobuf:"varint,3,opt,name=force_shutdown,json=forceShutdown,proto3" json:"force_shutdown,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ShutdownCommand) Reset() {
	*x = ShutdownCommand{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownCommand) ProtoMessage() {}

func (x *ShutdownCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownCommand.ProtoReflect.Descriptor instead.
func (*ShutdownCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ShutdownCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ShutdownCommand) GetGracePeriodSeconds() int32 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

func (x *ShutdownCommand) GetForceShutdown() bool {
	if x != nil {
		return x.ForceShutdown
	}
	return false
}

// 隧道请求
type TunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // ssh/telnet/rdp
	TargetHost    string                 `protobuf:"bytes,3,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	TargetPort    int32                  `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Credentials   *Credentials           `protobuf:"bytes,5,opt,name=credentials,proto3" json:"credentials,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Options       map[string]string      `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelRequest) Reset() {
	*x = TunnelRequest{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelRequest) ProtoMessage() {}

func (x *TunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelRequest.ProtoReflect.Descriptor instead.
func (*TunnelRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *TunnelRequest) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TunnelRequest) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *TunnelRequest) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *TunnelRequest) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *TunnelRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TunnelRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       *MetricsData           `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetMetrics() *MetricsData {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedConfig *AgentConfig           `protobuf:"bytes,3,opt,name=updated_config,json=updatedConfig,proto3" json:"updated_config,omitempty"` // 如果有配置更新
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetUpdatedConfig() *AgentConfig {
	if x != nil {
		return x.UpdatedConfig
	}
	return nil
}

// 任务状态请求
type TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TaskIds       []string               `protobuf:"bytes,2,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *TaskStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskStatusRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

// 任务状态响应
type TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskResults   []*TaskResult          `protobuf:"bytes,1,rep,name=task_results,json=taskResults,proto3" json:"task_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *TaskStatusResponse) GetTaskResults() []*TaskResult {
	if x != nil {
		return x.TaskResults
	}
	return nil
}

// 监控指标请求
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Metrics       *MetricsData           `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

func (x *MetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsRequest) GetMetrics() *MetricsData {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// 监控指标响应
type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *MetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\x8c\x03\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x123\n" +
	"\tresources\x18\x05 \x01(\v2\x15.agent.ResourceLimitsR\tresources\x125\n" +
	"\fnetwork_info\x18\x06 \x01(\v2\x12.agent.NetworkInfoR\vnetworkInfo\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.agent.RegisterRequest.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"auth_token\x18\b \x01(\tR\tauthToken\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vagent_token\x18\x03 \x01(\tR\n" +
	"agentToken\x12*\n" +
	"\x06config\x18\x04 \x01(\v2\x12.agent.AgentConfigR\x06config\"\xcc\x01\n" +
	"\x0eResourceLimits\x126\n" +
	"\x17max_concurrent_sessions\x18\x01 \x01(\x05R\x15maxConcurrentSessions\x12\"\n" +
	"\rmax_memory_mb\x18\x02 \x01(\x05R\vmaxMemoryMb\x12&\n" +
	"\x0fmax_cpu_percent\x18\x03 \x01(\x05R\rmaxCpuPercent\x126\n" +
	"\x17session_timeout_seconds\x18\x04 \x01(\x05R\x15sessionTimeoutSeconds\"\x84\x02\n" +
	"\vNetworkInfo\x12\x19\n" +
	"\blocal_ip\x18\x01 \x01(\tR\alocalIp\x12\x1b\n" +
	"\tpublic_ip\x18\x02 \x01(\tR\bpublicIp\x12)\n" +
	"\x10network_segments\x18\x03 \x03(\tR\x0fnetworkSegments\x12O\n" +
	"\x0fnetwork_latency\x18\x04 \x03(\v2&.agent.NetworkInfo.NetworkLatencyEntryR\x0enetworkLatency\x1aA\n" +
	"\x13NetworkLatencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xa3\x02\n" +
	"\vAgentConfig\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x01 \x01(\x05R\x18heartbeatIntervalSeconds\x12L\n" +
	"\x0eplugin_configs\x18\x02 \x03(\v2%.agent.AgentConfig.PluginConfigsEntryR\rpluginConfigs\x12'\n" +
	"\x0fallowed_targets\x18\x03 \x03(\tR\x0eallowedTargets\x12\x1d\n" +
	"\n" +
	"debug_mode\x18\x04 \x01(\bR\tdebugMode\x1a@\n" +
	"\x12PluginConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x03\n" +
	"\fAgentMessage\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x124\n" +
	"\theartbeat\x18\x04 \x01(\v2\x14.agent.HeartbeatDataH\x00R\theartbeat\x124\n" +
	"\vtask_result\x18\x05 \x01(\v2\x11.agent.TaskResultH\x00R\n" +
	"taskResult\x127\n" +
	"\ferror_report\x18\x06 \x01(\v2\x12.agent.ErrorReportH\x00R\verrorReport\x12.\n" +
	"\ametrics\x18\a \x01(\v2\x12.agent.MetricsDataH\x00R\ametrics\x12:\n" +
	"\rplugin_status\x18\b \x01(\v2\x13.agent.PluginStatusH\x00R\fpluginStatus\x12F\n" +
	"\x11connection_report\x18\t \x01(\v2\x17.agent.ConnectionReportH\x00R\x10connectionReportB\t\n" +
	"\apayload\"\xb1\x03\n" +
	"\n" +
	"OpsMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12+\n" +
	"\x04task\x18\x04 \x01(\v2\x15.agent.TaskAssignmentH\x00R\x04task\x12-\n" +
	"\x06config\x18\x05 \x01(\v2\x13.agent.ConfigUpdateH\x00R\x06config\x127\n" +
	"\fhealth_check\x18\x06 \x01(\v2\x12.agent.HealthCheckH\x00R\vhealthCheck\x125\n" +
	"\n" +
	"plugin_cmd\x18\a \x01(\v2\x14.agent.PluginCommandH\x00R\tpluginCmd\x124\n" +
	"\bshutdown\x18\b \x01(\v2\x16.agent.ShutdownCommandH\x00R\bshutdown\x12=\n" +
	"\x0etunnel_request\x18\t \x01(\v2\x14.agent.TunnelRequestH\x00R\rtunnelRequestB\t\n" +
	"\apayload\"\xd9\x02\n" +
	"\rHeartbeatData\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\x05R\x0eactiveSessions\x12*\n" +
	"\x11cpu_usage_percent\x18\x03 \x01(\x02R\x0fcpuUsagePercent\x12&\n" +
	"\x0fmemory_usage_mb\x18\x04 \x01(\x02R\rmemoryUsageMb\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12K\n" +
	"\rplugin_status\x18\x06 \x03(\v2&.agent.HeartbeatData.PluginStatusEntryR\fpluginStatus\x1a?\n" +
	"\x11PluginStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x02\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.agent.TaskStatusR\x06status\x12\x1f\n" +
	"\vresult_data\x18\x04 \x01(\tR\n" +
	"resultData\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12*\n" +
	"\x11execution_time_ms\x18\x06 \x01(\x03R\x0fexecutionTimeMs\x12;\n" +
	"\bmetadata\x18\a \x03(\v2\x1f.agent.TaskResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x02\n" +
	"\vErrorReport\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x1f\n" +
	"\vstack_trace\x18\x04 \x01(\tR\n" +
	"stackTrace\x129\n" +
	"\acontext\x18\x05 \x03(\v2\x1f.agent.ErrorReport.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x03\n" +
	"\vMetricsData\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12/\n" +
	"\x13successful_requests\x18\x02 \x01(\x03R\x12successfulRequests\x12'\n" +
	"\x0ffailed_requests\x18\x03 \x01(\x03R\x0efailedRequests\x127\n" +
	"\x18average_response_time_ms\x18\x04 \x01(\x02R\x15averageResponseTimeMs\x12/\n" +
	"\x13concurrent_sessions\x18\x05 \x01(\x05R\x12concurrentSessions\x12'\n" +
	"\x0fthroughput_mbps\x18\x06 \x01(\x02R\x0ethroughputMbps\x12R\n" +
	"\x10protocol_metrics\x18\a \x03(\v2'.agent.MetricsData.ProtocolMetricsEntryR\x0fprotocolMetrics\x1aB\n" +
	"\x14ProtocolMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xfa\x01\n" +
	"\fPluginStatus\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x127\n" +
	"\x06config\x18\x05 \x03(\v2\x1f.agent.PluginStatus.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\x10ConnectionReport\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\bR\tconnected\x12,\n" +
	"\x12connection_time_ms\x18\x04 \x01(\x03R\x10connectionTimeMs\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xbe\x03\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12,\n" +
	"\ttask_type\x18\x03 \x01(\x0e2\x0f.agent.TaskTypeR\btaskType\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1f\n" +
	"\vtarget_port\x18\x05 \x01(\x05R\n" +
	"targetPort\x124\n" +
	"\vcredentials\x18\x06 \x01(\v2\x12.agent.CredentialsR\vcredentials\x12\x18\n" +
	"\apayload\x18\a \x01(\tR\apayload\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12<\n" +
	"\aoptions\x18\n" +
	" \x03(\v2\".agent.TaskAssignment.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x02\n" +
	"\vCredentials\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vauth_method\x18\x05 \x01(\tR\n" +
	"authMethod\x123\n" +
	"\x05extra\x18\x06 \x03(\v2\x1d.agent.Credentials.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x01\n" +
	"\fConfigUpdate\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\tR\rconfigVersion\x12:\n" +
	"\aconfigs\x18\x02 \x03(\v2 .agent.ConfigUpdate.ConfigsEntryR\aconfigs\x12)\n" +
	"\x10restart_required\x18\x03 \x01(\bR\x0frestartRequired\x1a:\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\vHealthCheck\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\x12\x1e\n" +
	"\n" +
	"components\x18\x02 \x03(\tR\n" +
	"components\"\xcf\x01\n" +
	"\rPluginCommand\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12D\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2$.agent.PluginCommand.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x0fShutdownCommand\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x120\n" +
	"\x14grace_period_seconds\x18\x02 \x01(\x05R\x12gracePeriodSeconds\x12%\n" +
	"\x0eforce_shutdown\x18\x03 \x01(\bR\rforceShutdown\"\xd8\x02\n" +
	"\rTunnelRequest\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x1f\n" +
	"\vtarget_host\x18\x03 \x01(\tR\n" +
	"targetHost\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\x05R\n" +
	"targetPort\x124\n" +
	"\vcredentials\x18\x05 \x01(\v2\x12.agent.CredentialsR\vcredentials\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12;\n" +
	"\aoptions\x18\a \x03(\v2!.agent.TunnelRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12,\n" +
	"\ametrics\x18\x03 \x01(\v2\x12.agent.MetricsDataR\ametrics\"\x82\x01\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x0eupdated_config\x18\x03 \x01(\v2\x12.agent.AgentConfigR\rupdatedConfig\"I\n" +
	"\x11TaskStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\btask_ids\x18\x02 \x03(\tR\ataskIds\"J\n" +
	"\x12TaskStatusResponse\x124\n" +
	"\ftask_results\x18\x01 \x03(\v2\x11.agent.TaskResultR\vtaskResults\"Y\n" +
	"\x0eMetricsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12,\n" +
	"\ametrics\x18\x02 \x01(\v2\x12.agent.MetricsDataR\ametrics\"E\n" +
	"\x0fMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*{\n" +
	"\n" +
	"TaskStatus\x12\x10\n" +
	"\fTASK_PENDING\x10\x00\x12\x10\n" +
	"\fTASK_RUNNING\x10\x01\x12\x12\n" +
	"\x0eTASK_COMPLETED\x10\x02\x12\x0f\n" +
	"\vTASK_FAILED\x10\x03\x12\x10\n" +
	"\fTASK_TIMEOUT\x10\x04\x12\x12\n" +
	"\x0eTASK_CANCELLED\x10\x05*\x94\x01\n" +
	"\bTaskType\x12\x11\n" +
	"\rTUNNEL_CREATE\x10\x00\x12\x10\n" +
	"\fTUNNEL_CLOSE\x10\x01\x12\x13\n" +
	"\x0fCOMMAND_EXECUTE\x10\x02\x12\x14\n" +
	"\x10HARDWARE_CONTROL\x10\x03\x12\x11\n" +
	"\rNETWORK_PROBE\x10\x04\x12\x11\n" +
	"\rFILE_TRANSFER\x10\x05\x12\x12\n" +
	"\x0eSCRIPT_EXECUTE\x10\x062\xc7\x02\n" +
	"\fAgentService\x12;\n" +
	"\bRegister\x12\x16.agent.RegisterRequest\x1a\x17.agent.RegisterResponse\x124\n" +
	"\x06Stream\x12\x13.agent.AgentMessage\x1a\x11.agent.OpsMessage(\x010\x01\x12>\n" +
	"\tHeartbeat\x12\x17.agent.HeartbeatRequest\x1a\x18.agent.HeartbeatResponse\x12D\n" +
	"\rGetTaskStatus\x12\x18.agent.TaskStatusRequest\x1a\x19.agent.TaskStatusResponse\x12>\n" +
	"\rReportMetrics\x12\x15.agent.MetricsRequest\x1a\x16.agent.MetricsResponseB\tZ\a./agentb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_agent_proto_goTypes = []any{
	(TaskStatus)(0),            // 0: agent.TaskStatus
	(TaskType)(0),              // 1: agent.TaskType
	(*RegisterRequest)(nil),    // 2: agent.RegisterRequest
	(*RegisterResponse)(nil),   // 3: agent.RegisterResponse
	(*ResourceLimits)(nil),     // 4: agent.ResourceLimits
	(*NetworkInfo)(nil),        // 5: agent.NetworkInfo
	(*AgentConfig)(nil),        // 6: agent.AgentConfig
	(*AgentMessage)(nil),       // 7: agent.AgentMessage
	(*OpsMessage)(nil),         // 8: agent.OpsMessage
	(*HeartbeatData)(nil),      // 9: agent.HeartbeatData
	(*TaskResult)(nil),         // 10: agent.TaskResult
	(*ErrorReport)(nil),        // 11: agent.ErrorReport
	(*MetricsData)(nil),        // 12: agent.MetricsData
	(*PluginStatus)(nil),       // 13: agent.PluginStatus
	(*ConnectionReport)(nil),   // 14: agent.ConnectionReport
	(*TaskAssignment)(nil),     // 15: agent.TaskAssignment
	(*Credentials)(nil),        // 16: agent.Credentials
	(*ConfigUpdate)(nil),       // 17: agent.ConfigUpdate
	(*HealthCheck)(nil),        // 18: agent.HealthCheck
	(*PluginCommand)(nil),      // 19: agent.PluginCommand
	(*ShutdownCommand)(nil),    // 20: agent.ShutdownCommand
	(*TunnelRequest)(nil),      // 21: agent.TunnelRequest
	(*HeartbeatRequest)(nil),   // 22: agent.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 23: agent.HeartbeatResponse
	(*TaskStatusRequest)(nil),  // 24: agent.TaskStatusRequest
	(*TaskStatusResponse)(nil), // 25: agent.TaskStatusResponse
	(*MetricsRequest)(nil),     // 26: agent.MetricsRequest
	(*MetricsResponse)(nil),    // 27: agent.MetricsResponse
	nil,                        // 28: agent.RegisterRequest.MetadataEntry
	nil,                        // 29: agent.NetworkInfo.NetworkLatencyEntry
	nil,                        // 30: agent.AgentConfig.PluginConfigsEntry
	nil,                        // 31: agent.HeartbeatData.PluginStatusEntry
	nil,                        // 32: agent.TaskResult.MetadataEntry
	nil,                        // 33: agent.ErrorReport.ContextEntry
	nil,                        // 34: agent.MetricsData.ProtocolMetricsEntry
	nil,                        // 35: agent.PluginStatus.ConfigEntry
	nil,                        // 36: agent.TaskAssignment.OptionsEntry
	nil,                        // 37: agent.Credentials.ExtraEntry
	nil,                        // 38: agent.ConfigUpdate.ConfigsEntry
	nil,                        // 39: agent.PluginCommand.ParametersEntry
	nil,                        // 40: agent.TunnelRequest.OptionsEntry
}
var file_agent_proto_depIdxs = []int32{
	4,  // 0: agent.RegisterRequest.resources:type_name -> agent.ResourceLimits
	5,  // 1: agent.RegisterRequest.network_info:type_name -> agent.NetworkInfo
	28, // 2: agent.RegisterRequest.metadata:type_name -> agent.RegisterRequest.MetadataEntry
	6,  // 3: agent.RegisterResponse.config:type_name -> agent.AgentConfig
	29, // 4: agent.NetworkInfo.network_latency:type_name -> agent.NetworkInfo.NetworkLatencyEntry
	30, // 5: agent.AgentConfig.plugin_configs:type_name -> agent.AgentConfig.PluginConfigsEntry
	9,  // 6: agent.AgentMessage.heartbeat:type_name -> agent.HeartbeatData
	10, // 7: agent.AgentMessage.task_result:type_name -> agent.TaskResult
	11, // 8: agent.AgentMessage.error_report:type_name -> agent.ErrorReport
	12, // 9: agent.AgentMessage.metrics:type_name -> agent.MetricsData
	13, // 10: agent.AgentMessage.plugin_status:type_name -> agent.PluginStatus
	14, // 11: agent.AgentMessage.connection_report:type_name -> agent.ConnectionReport
	15, // 12: agent.OpsMessage.task:type_name -> agent.TaskAssignment
	17, // 13: agent.OpsMessage.config:type_name -> agent.ConfigUpdate
	18, // 14: agent.OpsMessage.health_check:type_name -> agent.HealthCheck
	19, // 15: agent.OpsMessage.plugin_cmd:type_name -> agent.PluginCommand
	20, // 16: agent.OpsMessage.shutdown:type_name -> agent.ShutdownCommand
	21, // 17: agent.OpsMessage.tunnel_request:type_name -> agent.TunnelRequest
	31, // 18: agent.HeartbeatData.plugin_status:type_name -> agent.HeartbeatData.PluginStatusEntry
	0,  // 19: agent.TaskResult.status:type_name -> agent.TaskStatus
	32, // 20: agent.TaskResult.metadata:type_name -> agent.TaskResult.MetadataEntry
	33, // 21: agent.ErrorReport.context:type_name -> agent.ErrorReport.ContextEntry
	34, // 22: agent.MetricsData.protocol_metrics:type_name -> agent.MetricsData.ProtocolMetricsEntry
	35, // 23: agent.PluginStatus.config:type_name -> agent.PluginStatus.ConfigEntry
	1,  // 24: agent.TaskAssignment.task_type:type_name -> agent.TaskType
	16, // 25: agent.TaskAssignment.credentials:type_name -> agent.Credentials
	36, // 26: agent.TaskAssignment.options:type_name -> agent.TaskAssignment.OptionsEntry
	37, // 27: agent.Credentials.extra:type_name -> agent.Credentials.ExtraEntry
	38, // 28: agent.ConfigUpdate.configs:type_name -> agent.ConfigUpdate.ConfigsEntry
	39, // 29: agent.PluginCommand.parameters:type_name -> agent.PluginCommand.ParametersEntry
	16, // 30: agent.TunnelRequest.credentials:type_name -> agent.Credentials
	40, // 31: agent.TunnelRequest.options:type_name -> agent.TunnelRequest.OptionsEntry
	12, // 32: agent.HeartbeatRequest.metrics:type_name -> agent.MetricsData
	6,  // 33: agent.HeartbeatResponse.updated_config:type_name -> agent.AgentConfig
	10, // 34: agent.TaskStatusResponse.task_results:type_name -> agent.TaskResult
	12, // 35: agent.MetricsRequest.metrics:type_name -> agent.MetricsData
	2,  // 36: agent.AgentService.Register:input_type -> agent.RegisterRequest
	7,  // 37: agent.AgentService.Stream:input_type -> agent.AgentMessage
	22, // 38: agent.AgentService.Heartbeat:input_type -> agent.HeartbeatRequest
	24, // 39: agent.AgentService.GetTaskStatus:input_type -> agent.TaskStatusRequest
	26, // 40: agent.AgentService.ReportMetrics:input_type -> agent.MetricsRequest
	3,  // 41: agent.AgentService.Register:output_type -> agent.RegisterResponse
	8,  // 42: agent.AgentService.Stream:output_type -> agent.OpsMessage
	23, // 43: agent.AgentService.Heartbeat:output_type -> agent.HeartbeatResponse
	25, // 44: agent.AgentService.GetTaskStatus:output_type -> agent.TaskStatusResponse
	27, // 45: agent.AgentService.ReportMetrics:output_type -> agent.MetricsResponse
	41, // [41:46] is the sub-list for method output_type
	36, // [36:41] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_TaskResult)(nil),
		(*AgentMessage_ErrorReport)(nil),
		(*AgentMessage_Metrics)(nil),
		(*AgentMessage_PluginStatus)(nil),
		(*AgentMessage_ConnectionReport)(nil),
	}
	file_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*OpsMessage_Task)(nil),
		(*OpsMessage_Config)(nil),
		(*OpsMessage_HealthCheck)(nil),
		(*OpsMessage_PluginCmd)(nil),
		(*OpsMessage_Shutdown)(nil),
		(*OpsMessage_TunnelRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
